# Generated by Django 5.0.6 on 2024-06-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_alter_reservation_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_identifier',
            field=models.CharField(default='default_identifier', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_b', 'Parking B'), ('parking_a', 'Parking A')], max_length=50, null=True),
        ),
    ]
