# Generated by Django 5.0.6 on 2024-06-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_notification_event_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10, null=True),
        ),
    ]
