# Generated by Django 5.0.6 on 2024-06-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_alter_reservation_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guarantee',
            field=models.CharField(blank=True, choices=[('money', 'Money'), ('passport', 'Passport')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_a', 'Parking A'), ('parking_b', 'Parking B')], max_length=50, null=True),
        ),
    ]
