# Generated by Django 5.0.6 on 2024-06-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0009_notification_is_read_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_b', 'Parking B'), ('parking_a', 'Parking A')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('ended', 'Ended'), ('active', 'Active')], default='active', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('bank_check', 'Bank Check')], max_length=50)),
                ('entry_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='car_rental.client')),
                ('entry_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='car_rental.worker')),
            ],
        ),
    ]
