# Generated by Django 5.0.6 on 2024-06-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0010_alter_reservation_parking_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='description',
            new_name='entry_description',
        ),
        migrations.RenameField(
            model_name='spend',
            old_name='mode',
            new_name='entry_mode',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_a', 'Parking A'), ('parking_b', 'Parking B')], max_length=50, null=True),
        ),
    ]
