# Generated by Django 5.0.6 on 2024-06-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0011_rename_description_spend_entry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='expense_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='spend',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spend',
            name='expense_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='spend',
            name='expense_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_check', 'Bank Check')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spend',
            name='expenseclient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_spends', to='car_rental.client'),
        ),
        migrations.AddField(
            model_name='spend',
            name='expenseworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_spends', to='car_rental.worker'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='entry_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='entry_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_spends', to='car_rental.client'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='entry_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_check', 'Bank Check')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='entry_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_spends', to='car_rental.worker'),
        ),
    ]
