# Generated by Django 5.0.6 on 2024-06-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0012_spend_expense_amount_spend_expense_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='expenseclient',
            new_name='expense_client',
        ),
        migrations.RenameField(
            model_name='spend',
            old_name='expenseworker',
            new_name='expense_worker',
        ),
    ]
