# Generated by Django 5.0.6 on 2024-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0013_rename_expenseclient_spend_expense_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='fuel_gas',
            new_name='end_mileage',
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10, null=True),
        ),
    ]
