# Generated by Django 5.0.6 on 2024-06-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0014_rename_fuel_gas_reservation_end_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_b', 'Parking B'), ('parking_a', 'Parking A')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('ended', 'Ended'), ('active', 'Active')], default='active', max_length=10, null=True),
        ),
    ]
