# Generated by Django 5.0.6 on 2024-06-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0015_alter_reservation_parking_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_a', 'Parking A'), ('parking_b', 'Parking B')], max_length=50, null=True),
        ),
    ]
