# Generated by Django 5.0.6 on 2024-06-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0021_invoices_delete_invoicestep1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
    ]
