# Generated by Django 5.0.6 on 2024-06-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0023_alter_reservation_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_start', models.DateField()),
                ('insurance_end', models.DateField()),
                ('technical_visit', models.DateField(blank=True, null=True)),
                ('oil_change', models.IntegerField(blank=True, null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_rental.car')),
            ],
        ),
    ]
