# Generated by Django 5.0.6 on 2024-06-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0024_alter_reservation_status_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.CharField(blank=True, choices=[('parking_a', 'Parking A'), ('parking_b', 'Parking B')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('ended', 'Ended'), ('active', 'Active')], default='active', max_length=10, null=True),
        ),
    ]
